const merchItems = [
    { id: 1, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 3, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt2.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 4, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt3.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 5, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt4.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 6, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt5.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 7, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt6.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 8, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt7.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 9, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt8.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 10, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt9.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 11, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt10.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 12, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt11.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 13, name: 'T-Shirt', price: 120, image: new URL('/merch/t-shirt12.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun T-shirt' },
    { id: 14, name: 'Blanket', price: 185, image: new URL('/curtain/blanket.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Blanket' },
    { id: 15, name: 'Blanket', price: 185, image: new URL('/curtain/blanket2.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Blanket' },
    { id: 16, name: 'Blanket', price: 185, image: new URL('/curtain/blanket3.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Blanket' },
    { id: 17, name: 'Blanket', price: 185, image: new URL('/curtain/blanket4.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Blanket' },
    { id: 18, name: 'Blanket', price: 185, image: new URL('/curtain/blanket5.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Blanket' },
    { id: 19, name: 'Blanket', price: 185, image: new URL('/curtain/blanket6.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Blanket' },
    { id: 20, name: 'Curtain', price: 145, image: new URL('/curtain/curtain.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Curtain' },
    { id: 21, name: 'Curtain', price: 145, image: new URL('/curtain/curtain1.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Curtain' },
    { id: 22, name: 'Curtain', price: 145, image: new URL('/curtain/curtain2.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Curtain' },
    { id: 23, name: 'Curtain', price: 145, image: new URL('/curtain/curtain3.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Curtain' },
    { id: 24, name: 'Curtain', price: 145, image: new URL('/curtain/curtain4.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Curtain' },
    { id: 25, name: 'Mug', price: 60, image: new URL('/curtain/mug.jpg', import.meta.url).href, description: 'Limited Lee Byung Hun Mug' },
  ];
  
  const auctionItems = [
    { id: 101, name: 'Plaid Down Jacket', price: 3250, image: new URL('/auction/auction.jpg', import.meta.url).href, description: 'His Moncler Collection' },
    { id: 102, name: 'Full-Zip Overshirt', price: 5000, image: new URL('/auction/auction1.jpg', import.meta.url).href, description: 'His Zegna Suede Collection 2025' },
    { id: 103, name: 'Woven Nappa Leather Jacket', price: 16000, image: new URL('/auction/auction2.jpg', import.meta.url).href, description: 'His D&G Collection 2025' },
    { id: 104, name: 'Luxe Suede Trucker Jacket', price: 2500, image: new URL('/auction/auction3.jpg', import.meta.url).href, description: 'His Ralph Lauren Collection' },
    { id: 105, name: 'Grenoble Fall', price: 4000, image: new URL('/auction/auction4.jpg', import.meta.url).href, description: 'His Moncler 2017 Collection' },
    { id: 106, name: '4-Bar Argyle Merino', price: 1200, image: new URL('/auction/auction5.jpg', import.meta.url).href, description: 'His Thombrowne Collection' },
    { id: 107, name: 'Baby Cashmere Cardigan', price: 2500, image: new URL('/auction/auction6.jpg', import.meta.url).href, description: 'His LoroPiana Fobello Collection 2025' },
    { id: 108, name: 'Light Windbreaker Jacket', price: 2950, image: new URL('/auction/auction7.jpg', import.meta.url).href, description: 'His Versace Collection' },
    { id: 109, name: 'Herringbone Wool Jacket', price: 4000, image: new URL('/auction/auction8.jpg', import.meta.url).href, description: 'His Ralph lauren Collection 2025' },
    { id: 110, name: 'Logo-Print Shirt', price: 11850, image: new URL('/auction/auction9.jpg', import.meta.url).href, description: 'His Alexander McQueen Collection 2022' },
    { id: 111, name: 'Too Deadly But Cute Hoodie', price: 1200, image: new URL('/auction/auction10.jpg', import.meta.url).href, description: 'Dysfunct 2021 Collection' },
    { id: 112, name: 'Leather Trench Coat', price: 6000, image: new URL('/auction/auction11.jpg', import.meta.url).href, description: 'His Tom Ford Coat Collection 2025' },
    { id: 113, name: 'Virgin Wool-Blend Jumper', price: 1200, image: new URL('/auction/auction12.jpg', import.meta.url).href, description: 'His Emperio Armani Collection 2016' },
    { id: 114, name: 'Moline Ombre', price: 1950, image: new URL('/auction/auction13.jpg', import.meta.url).href, description: 'His Hermes Collection 2022' },
    { id: 115, name: 'Leo Hooded Down Biker Jacket', price: 3500, image: new URL('/auction/auction14.jpg', import.meta.url).href, description: 'His Moncler Collection' },
    { id: 116, name: 'Cotton Twill Jacket', price: 3000, image: new URL('/auction/auction15.jpg', import.meta.url).href, description: 'His Ralph Lauren Collection 2025' },
    { id: 117, name: 'Handmade Purple Cashmere Blazer', price: 3089, image: new URL('/auction/auction16.jpg', import.meta.url).href, description: 'His Ralph Lauren Collection 2025' },
    { id: 118, name: 'Purple Label Glen Cashmere Sweater', price: 950, image: new URL('/auction/auction17.jpg', import.meta.url).href, description: 'His Ralph Lauren Collection' },
    { id: 119, name: 'Roll Neck Jumper', price: 1800, image: new URL('/auction/auction18.jpg', import.meta.url).href, description: 'His Brunello Cucinelli Collection' },
    { id: 120, name: 'Leather Biker Jacket', price: 120, image: new URL('/auction/auction19.jpg', import.meta.url).href, description: 'His Versace Collection 2024' },
    { id: 121, name: 'Montedoro Franchigia Jacket', price: 1800, image: new URL('/auction/auction20.jpg', import.meta.url).href, description: 'His Slowear Collection 2021' },
    { id: 122, name: 'Hand-Tailored Wool-Cashmere Topcoat', price: 1650, image: new URL('/auction/auction21.jpg', import.meta.url).href, description: 'His Ralph Lauren Collection 2025' },
    { id: 123, name: 'Shearking Bomber Jacket', price: 120, image: new URL('/auction/auction22.jpg', import.meta.url).href, description: 'His Brunello Cucinelli Collection' },
    { id: 124, name: 'Paint', price: 600, image: new URL('/curtain/paint.jpg', import.meta.url).href, description: 'His Limited Paint' },
    { id: 125, name: 'Pillow', price: 800, image: new URL('/curtain/pillow.jpg', import.meta.url).href, description: 'His Limited Pillow' },
    { id: 126, name: 'Portrait', price: 1450, image: new URL('/curtain/portrait.jpg', import.meta.url).href, description: 'His Limited Self Portrait' },
    { id: 127, name: 'Portrait', price: 1450, image: new URL('/curtain/portrait1.jpg', import.meta.url).href, description: 'His Limited Self Portrait' },
    { id: 128, name: 'Sticker', price: 300, image: new URL('/curtain/sticker.jpg', import.meta.url).href, description: 'His Limited Sticker' },
    { id: 129, name: 'Sticker', price: 300, image: new URL('/curtain/stickerr.jpg', import.meta.url).href, description: 'His Limited Sticker' },
    { id: 130, name: 'Sticker', price: 300, image: new URL('/curtain/sticker1.jpg', import.meta.url).href, description: 'His Limited Sticker' },
  ];
  
  const squidGameMerch = [
    { id: 200, name: '001, Motion Detector & 230 Portrait', price: 350, image: new URL('/sqidgames/squid.jpg', import.meta.url).href, description: 'Limited Squid Games Merch' },
    { id: 201, name: 'Squid Game Buttons', price: 350, image: new URL('/sqidgames/squid2.jpg', import.meta.url).href, description: 'Limited Squid Games Merch' },
    { id: 202, name: 'Players Stickers', price: 350, image: new URL('/sqidgames/squid3.jpg', import.meta.url).href, description: 'Limited Squid Games Merch' },
    { id: 203, name: 'The FrontMan Bag', price: 350, image: new URL('/sqidgames/squid4.jpg', import.meta.url).href, description: 'Limited Squid Games Merch' },
    { id: 204, name: 'Player 230 Necklace', price: 350, image: new URL('/sqidgames/squid5.jpg', import.meta.url).href, description: 'Limited Squid Games Merch' },
    { id: 205, name: 'Squid Game Buttons', price: 350, image: new URL('/sqidgames/squiddice.jpg', import.meta.url).href, description: 'Limited Squid Games Merch' },
    { id: 206, name: 'Squid Game Busquit Outline', price: 350, image: new URL('/sqidgames/squidgame.jpg', import.meta.url).href, description: 'Limited Squid Games Merch' },
  ];

  const bookMerch = [
    {
      id: 300,
      name: 'Lee Byung Hun Photo Album',
      price: 650,
      image: new URL('/curtain/book.jpg', import.meta.url).href,
      image: new URL('/curtain/book1.jpg', import.meta.url).href,
      description: 'Limited Photo Album, English & Japanese Edition',
    },
    {
      id: 301,
      name: 'Lee Byung Hun Photobook',
      price: 500,
      image: new URL('/curtain/book2.jpg', import.meta.url).href,
      image: new URL('/curtain/book3.jpg', import.meta.url).href,
      image: new URL('/curtain/book6.jpg', import.meta.url).href,
      image: new URL('/curtain/book4.jpg', import.meta.url).href,
      image: new URL('/curtain/book5.jpg', import.meta.url).href,
      description: 'K-POP Photobook Limited Edition',
    },
  ];
  
  export { merchItems, auctionItems, squidGameMerch, bookMerch };
  